global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'anubis'
    # metrics_path: /
    static_configs:
      - targets: ['anubis:9090']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
